### ISSUE TITLE
Hide View Conversation link for non-logged-in users

### ISSUE THREAD

**Issue by pranali333** [rtMediaWP/rtMedia#1161]
View Conversation link is used to display the complete ongoing comments with the parent activity.
This link should be visible to only members of the website.

Currently, the conversation is not visible to non-members but the button/link in lightbox is still there and redirects to a not found page.

We should hide the link and button for not logged in users.

![view-conversation-non-logged-in](https://user-images.githubusercontent.com/7771963/42555707-ce275e9a-8506-11e8-9724-3c9f3746a3bf.PNG)

![view-conversation-activity-feed](https://user-images.githubusercontent.com/7771963/42555715-da2fd88e-8506-11e8-8459-9ea298fa29b5.PNG)

Thanks,

**Comment by kjnanda** [comment]
Yes, We should work on this.

**Comment by vermadarsh** [comment]
Hi @pooja-muchandikar 

I tested this with the following environment details:
rtMedia: v4.5.11
BuddyPress: v5.1.2
WordPress: v5.3.2

I'm unable to replicate this issue as the button labeled `View Conversation` redirects me to a simple conversation page, rather than a 404 error page.

**Comment by pooja-muchandikar** [comment]
I have cross-checked the issue and following are my findings:

- Firstly, for non-logged in users the private and friends and logged-in users privacy set posts are not visible. Since, the posts itself are not visible the view conversation link hiding is invalid here

- For public posts the view conversation link is visible and it redirects to respective conversation as expected. 

- Checked in lightbox view and in single media as well 

Closing this issue for now.
