### ISSUE TITLE
Traductions by Loco Translate don't work

### ISSUE THREAD

**Issue by BarbaraGo** [rtMediaWP/rtMedia#1166]
I can't translate these parts of plugin with Loco Translate.
Furthermore when i upload a photo or a comment i don't see date and time where I uploaded this, but only the word "fa". 

![schermata 2018-07-11 alle 16 19 02](https://user-images.githubusercontent.com/41119335/42578139-373b5034-8526-11e8-9418-e16e9bc9a582.png)
![schermata 2018-07-11 alle 16 18 25](https://user-images.githubusercontent.com/41119335/42578141-375abe74-8526-11e8-825b-0d1c3c13f414.png)
![schermata 2018-07-11 alle 16 18 04](https://user-images.githubusercontent.com/41119335/42578143-3776044a-8526-11e8-8dc1-993b6b55955e.png)
![schermata 2018-07-11 alle 16 17 45](https://user-images.githubusercontent.com/41119335/42578144-3797a83e-8526-11e8-8d59-e270af0ada32.png)

Could you help me please?

**Comment by BarbaraGo** [comment]
Any news about this please?

**Comment by pranali333** [comment]
Hello,

I am checking your issue with our team. I will update you soon on this.

Thanks for your patience.

**Comment by sudhir-yadav** [comment]
Hi BarbaraGo,

I checked your query regarding translation text and found that everything is working fine at my end. I am still not sure about working of `Loco Translate`. But if you find any thing missing, you can always help us translate plugin in your preferred language. 
https://translate.wordpress.org/projects/wp-plugins/buddypress-media/dev

please feel free to mention your queries , so that I could assist you better.

Thank you

**Comment by kjnanda** [comment]
Hi @BarbaraGo,

I hope you are doing good!

It is been quite a long time we have not heard from you. I hope your query is been addressed. So I am closing this ticket. However, please feel free to open a new ticket for any queries.

Regards,
Krupa
