### ISSUE TITLE
[Customer Query] German umlauts are displayed incorrectly when using "Read More".

### ISSUE THREAD

**Issue by Polarwelt** [rtMediaWP/rtMedia#1564]
Hello everybody,

i have the problem that in the activity stream of Buddypress the umlauts are displayed incorrectly when using "Read More". If you display the whole post, this is displayed correctly.

This only happens if images were added via rtMedia. If pure text is wrapped by "Read More", the umlauts are displayed correctly.

Test environment:
Wordpress: 5.3.2
BuddyPress: 5.1.2
rtMedia: 4.6.0
Themes: OceanWP, Nirvana (CryoutCreations), Twenty Seventeen

Greeting Polarwelt

![rtmedia1](https://user-images.githubusercontent.com/20779887/75387865-444e6e80-58e4-11ea-8b22-2efeca91eb3d.png)
![rtmedia2](https://user-images.githubusercontent.com/20779887/75387873-46b0c880-58e4-11ea-8aa3-fe859ab7b60b.png)

**Comment by pooja-muchandikar** [comment]
Hi @Polarwelt 

> If pure text is wrapped by "Read More", the umlauts are displayed correctly.

We have added this enhancement on customer requests. Complete text will be shown on click of read more option.

Do you want to show complete text first and then on click of read more want to view the image? Is this your requirement? 

I would like to request you to open a new support ticket on our support channel - https://rtmedia.io/support

We can continue our discussion over support channel.

Regards,
Pooja

**Comment by kjnanda** [comment]
Hi @Polarwelt,

I hope you are doing good.

Based on the conversation you had with Pooja, I found that we are already having the communication on our support channel. So I am closing this ticket from here.

Have a nice day! 

Regards,
Krupa

**Comment by kjnanda** [comment]
Hi @Polarwelt,

I hope you are doing good!

We have released a new version of the rtMedia core. This latest release has the fix for the concern you shared. Please check out the full changelog here - https://wordpress.org/plugins/buddypress-media/#developers

Please update the plugin using the plugin update notification from the dashboard or you can download the new zip file from [here](https://wordpress.org/plugins/buddypress-media/) as well.

Please feel free to drop us any queries if you have. We will be happy to assist you in the same manner ahead.

We are glad to have you as our customer and we strive to make your experience better. We would appreciate it if you could give us your valuable feedback on rtMedia as a plugin and how it has helped you. This can help us serve you better.

You can add your review here - https://wordpress.org/support/plugin/buddypress-media/reviews/?filter=5

Have a nice day!
Stay safe!

Regards,
Krupa
