### ISSUE TITLE
Social Sharing - Need to be able to share specific image within Lightboxed album

### ISSUE THREAD

**Issue by darrenfulton** [rtMediaWP/rtMedia#752]
So, I'm on the site and am looking at an image that I like within an album (see attached image_screeenshot_1.png), when I share that, I want people to click that link and see what I'm specifically sharing.  It should look like what I was looking at when I clicked the "share" icon.  I should see the lightboxed image within the album that I was looking at when I clicked a share icon.

Instead of this (see attached image_screenshot_2.png
![image_screenshot_2](https://cloud.githubusercontent.com/assets/11380955/19490280/26eff736-9534-11e6-967c-2cff36a30c5f.png)
![image_screeenshot_1](https://cloud.githubusercontent.com/assets/11380955/19490281/26f220ce-9534-11e6-80c8-3a8c35f42db8.png)

).  Also, please add a URL icon for displaying a URL to that part of an album, so that people can just copy and paste into an IM or an email or whatever.

**Comment by Gdad** [comment]
Hello @darrenfulton, 
If i am not wrong you want user to see media in lightbox, if you shared that media from lightbox. 

basically its not possible to implement it like this because when you share something with third party actually we share our site link.
its not possible for now to open that media in lightbox.

**Comment by Gdad** [comment]
Hello @darrenfulton,

If I am not wrong you want a user to see media in Lightbox when it is shared from a Lightbox. 
This is not possible because the link that gets shared via the Share buttons is actually the permalink of the file. A lightbox is generated by JavaScript only on the `onClick` event. 
 
 Regarding your URL icon query, could you please elaborate on your requirement? From what I understood, you would like an icon to copy the link to the current album page. 

Regards,

Naveen Giri

**Comment by kjnanda** [comment]
Closing this issue since no more information was provided from the customer then after.
